/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const LOS_WAITMODE_AND: u32 = 4;
pub const LOS_WAITMODE_OR: u32 = 2;
pub const LOS_WAITMODE_CLR: u32 = 1;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
#[doc = " @ingroup los_list\n Structure of a node in a doubly linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOS_DL_LIST {
    #[doc = "< Current node's pointer to the previous node"]
    pub pstPrev: *mut LOS_DL_LIST,
    #[doc = "< Current node's pointer to the next node"]
    pub pstNext: *mut LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOS_DL_LIST"][::std::mem::size_of::<LOS_DL_LIST>() - 16usize];
    ["Alignment of LOS_DL_LIST"][::std::mem::align_of::<LOS_DL_LIST>() - 8usize];
    ["Offset of field: LOS_DL_LIST::pstPrev"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstPrev) - 0usize];
    ["Offset of field: LOS_DL_LIST::pstNext"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstNext) - 8usize];
};
#[doc = " @ingroup los_event\n Event control structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagEvent {
    #[doc = "< Event mask in the event control block,\nindicating the event that has been logically processed."]
    pub uwEventID: UINT32,
    #[doc = "< Event control block linked list"]
    pub stEventList: LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagEvent"][::std::mem::size_of::<tagEvent>() - 24usize];
    ["Alignment of tagEvent"][::std::mem::align_of::<tagEvent>() - 8usize];
    ["Offset of field: tagEvent::uwEventID"][::std::mem::offset_of!(tagEvent, uwEventID) - 0usize];
    ["Offset of field: tagEvent::stEventList"]
        [::std::mem::offset_of!(tagEvent, stEventList) - 8usize];
};
#[doc = " @ingroup los_event\n Event control structure"]
pub type EVENT_CB_S = tagEvent;
#[doc = " @ingroup los_event\n Event control structure"]
pub type PEVENT_CB_S = *mut tagEvent;
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Initialize an event control block.\n\n @par Description:\n This API is used to initialize the event control block pointed to by eventCB.\n @attention\n <ul>\n <li>None.</li>\n </ul>\n\n @param eventCB [IN/OUT] Pointer to the event control block to be initialized.\n\n @retval #LOS_ERRNO_EVENT_PTR_NULL  Null pointer.\n @retval #LOS_OK                    The event control block is successfully initialized.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventClear"]
    pub fn LOS_EventInit(eventCB: PEVENT_CB_S) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Obtain an event specified by the event ID.\n\n @par Description:\n This API is used to check whether an event expected by the user occurs according to the event ID, event mask,\n and event reading mode, and process the event based on the event reading mode. The event ID must point to\n valid memory.\n @attention\n <ul>\n <li>When the mode is LOS_WAITMODE_CLR, the eventID is passed-out.</li>\n <li>Otherwise the eventID is passed-in.</li>\n </ul>\n\n @param eventID      [IN/OUT] Pointer to the ID of the event to be checked.\n @param eventMask    [IN] Mask of the event expected to occur by the user, indicating the event obtained after\n it is logically processed that matches the ID pointed to by mode.\n @param mode         [IN] Event reading mode. The modes include LOS_WAITMODE_AND, LOS_WAITMODE_OR, LOS_WAITMODE_CLR.\n\n @retval 0             The event expected by the user does not occur.\n @retval #UINT32       The event expected by the user occurs.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventRead | LOS_EventWrite"]
    pub fn LOS_EventPoll(eventID: *mut UINT32, eventMask: UINT32, mode: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Read an event.\n\n @par Description:\n This API is used to block or schedule a task that reads an event of which the event control block, event mask,\n reading mode,\n and timeout information are specified.\n </ul>\n @attention\n <ul>\n <li>An error code and an event return value can be same. To differentiate the error code and return value, bit 25 of\n the event mask is forbidden to be used.</li>\n </ul>\n\n @param eventCB      [IN/OUT] Pointer to the event control block to be checked. This parameter must point to\n                              valid memory.\n @param eventMask    [IN]     Mask of the event expected to occur by the user, indicating the event obtained after\n                              it is logically processed that matches the ID pointed to by eventID.\n @param mode         [IN]     Event reading mode.\n @param timeOut      [IN]     Timeout interval of event reading (unit: Tick).\n\n @retval #LOS_ERRNO_EVENT_SETBIT_INVALID     Bit 25 of the event mask cannot be set because\n                                             it is set to an error number.\n @retval #LOS_ERRNO_EVENT_EVENTMASK_INVALID  The passed-in event reading mode is incorrect.\n @retval #LOS_ERRNO_EVENT_READ_IN_INTERRUPT  The event is being read during an interrupt.\n @retval #LOS_ERRNO_EVENT_FLAGS_INVALID      The event mode is invalid.\n @retval #LOS_ERRNO_EVENT_READ_IN_LOCK       The event reading task is locked.\n @retval #LOS_ERRNO_EVENT_PTR_NULL           The passed-in pointer is null.\n @retval 0                                   The event expected by the user does not occur.\n @retval #UINT32                             The event expected by the user occurs.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventPoll | LOS_EventWrite"]
    pub fn LOS_EventRead(
        eventCB: PEVENT_CB_S,
        eventMask: UINT32,
        mode: UINT32,
        timeOut: UINT32,
    ) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Write an event.\n\n @par Description:\n This API is used to write an event specified by the passed-in event mask into an event control block\n pointed to by eventCB.\n @attention\n <ul>\n <li>To determine whether the LOS_EventRead API returns an event or an error code, bit 25 of the event mask\n is forbidden to be used.</li>\n </ul>\n\n @param eventCB  [IN/OUT] Pointer to the event control block into which an event is to be written.\n This parameter must point to valid memory.\n @param events   [IN] Event mask to be written.\n\n @retval #LOS_ERRNO_EVENT_SETBIT_INVALID  Bit 25 of the event mask cannot be set to an event\n because it is set to an error code.\n @retval #LOS_ERRNO_EVENT_PTR_NULL        Null pointer.\n @retval #LOS_OK                          The event is successfully written.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventPoll | LOS_EventRead"]
    pub fn LOS_EventWrite(eventCB: PEVENT_CB_S, events: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Clear the event of the eventCB by a specified eventMask.\n\n @par Description:\n <ul>\n <li>This API is used to set the ID of an event that has a specified mask and of which the information is stored in\n an event control block pointed to by eventCB to 0. eventCB must point to valid memory.</li>\n </ul>\n @attention\n <ul>\n <li>The value of events needs to be reversed when it is passed-in.</li>\n </ul>\n\n @param eventCB     [IN/OUT] Pointer to the event control block to be cleared.\n @param eventMask   [IN]     Mask of the event to be cleared.\n\n @retval #LOS_ERRNO_EVENT_PTR_NULL  Null pointer.\n @retval #LOS_OK                    The event is successfully cleared.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventPoll | LOS_EventRead | LOS_EventWrite"]
    pub fn LOS_EventClear(eventCB: PEVENT_CB_S, eventMask: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_event\n @brief Destroy an event.\n\n @par Description:\n <ul>\n <li>This API is used to Destroy an event.</li>\n </ul>\n @attention\n <ul>\n <li>The specific event should be a valid one.</li>\n </ul>\n\n @param eventCB     [IN/OUT] Pointer to the event control block to be Destroyed.\n\n @retval #LOS_ERRNO_EVENT_PTR_NULL Null pointer.\n @retval #LOS_OK                   The event is successfully cleared.\n @par Dependency:\n <ul><li>los_event.h: the header file that contains the API declaration.</li></ul>\n @see LOS_EventPoll | LOS_EventRead | LOS_EventWrite"]
    pub fn LOS_EventDestroy(eventCB: PEVENT_CB_S) -> UINT32;
}
unsafe extern "C" {
    pub fn OsEventReadOnce(
        eventCB: PEVENT_CB_S,
        eventMask: UINT32,
        mode: UINT32,
        timeOut: UINT32,
    ) -> UINT32;
}
unsafe extern "C" {
    pub fn OsEventWriteOnce(eventCB: PEVENT_CB_S, events: UINT32) -> UINT32;
}
