/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const OS_SYS_CLOCK: u32 = 1000000;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND: u32 = 100;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND_MINI: u32 = 1000;
pub const LOSCFG_BASE_CORE_TICK_PERIOD_MS: u32 = 10;
pub const LOSCFG_BASE_CORE_TICK_WTIMER: u32 = 0;
pub const LOSCFG_BASE_CORE_TICK_RESPONSE_MAX: u32 = 0;
pub const LOSCFG_PLATFORM_HWI: u32 = 1;
pub const LOSCFG_USE_SYSTEM_DEFINED_INTERRUPT: u32 = 1;
pub const LOSCFG_PLATFORM_HWI_LIMIT: u32 = 32;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_PRIO: u32 = 10;
pub const LOSCFG_BASE_CORE_TSK_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_IDLE_STACK_SIZE: u32 = 384;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_TIMESLICE: u32 = 1;
pub const LOSCFG_BASE_CORE_TIMESLICE_TIMEOUT: u32 = 20000;
pub const LOSCFG_BASE_CORE_TSK_MONITOR: u32 = 0;
pub const LOSCFG_BASE_CORE_EXC_TSK_SWITCH: u32 = 0;
pub const LOS_TASK_PRIORITY_HIGHEST: u32 = 0;
pub const LOS_TASK_PRIORITY_LOWEST: u32 = 31;
pub const LOSCFG_BASE_CORE_TASKSTACK_INDEPENDENT: u32 = 0;
pub const LOSCFG_STACK_POINT_ALIGN_SIZE: u32 = 8;
pub const LOSCFG_BASE_IPC_SEM: u32 = 1;
pub const LOSCFG_BASE_IPC_SEM_LIMIT: u32 = 6;
pub const OS_SEM_COUNTING_MAX_COUNT: u32 = 65535;
pub const LOSCFG_BASE_IPC_MUX: u32 = 1;
pub const LOSCFG_BASE_IPC_MUX_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_QUEUE: u32 = 1;
pub const LOSCFG_BASE_IPC_QUEUE_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_STATIC_QUEUE_LIMIT: u32 = 3;
pub const LOSCFG_BASE_CORE_SWTMR: u32 = 1;
pub const LOSCFG_BASE_CORE_SWTMR_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_SWTMR_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_SWTMR_ALIGN: u32 = 0;
pub const OS_SWTMR_HANDLE_QUEUE_SIZE: u32 = 5;
pub const LOS_COMMON_DIVISOR: u32 = 10;
pub const LOSCFG_SYS_EXTERNAL_HEAP: u32 = 0;
pub const LOSCFG_SYS_HEAP_SIZE: u32 = 65536;
pub const LOSCFG_MEM_MUL_POOL: u32 = 1;
pub const LOSCFG_MEM_FREE_BY_TASKID: u32 = 0;
pub const LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK: u32 = 0;
pub const LOSCFG_MEM_OMIT_LR_CNT: u32 = 4;
pub const LOSCFG_MEM_RECORD_LR_CNT: u32 = 3;
pub const LOSCFG_MEM_LEAKCHECK_RECORD_MAX_NUM: u32 = 1024;
pub const LOSCFG_MEM_WATERLINE: u32 = 1;
pub const OS_SYS_MEM_NUM: u32 = 20;
pub const OS_SYS_NOCACHEMEM_SIZE: u32 = 0;
pub const LOSCFG_MEM_MUL_REGIONS: u32 = 0;
pub const LOSCFG_EXC_HARDWARE_STACK_PROTECTION: u32 = 0;
pub const CMSIS_OS_VER: u32 = 2;
pub const LOSCFG_KERNEL_PRINTF: u32 = 1;
pub const LOSCFG_MPU_ENABLE: u32 = 0;
pub const LOSCFG_TASK_MEM_USED: u32 = 0;
pub const LOSCFG_PLATFORM_HWI_WITH_ARG: u32 = 0;
pub const LOSCFG_ARCH_HWI_VECTOR_ALIGN: u32 = 256;
pub const LOSCFG_KERNEL_SIGNAL: u32 = 0;
pub const LOSCFG_KERNEL_PM: u32 = 0;
pub const LOSCFG_KERNEL_PM_IDLE: u32 = 0;
pub const LOSCFG_SHELL_STACK_SIZE: u32 = 4096;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static mut m_aucSysMem0: *mut UINT8;
}
#[doc = " @ingroup los_list\n Structure of a node in a doubly linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOS_DL_LIST {
    #[doc = "< Current node's pointer to the previous node"]
    pub pstPrev: *mut LOS_DL_LIST,
    #[doc = "< Current node's pointer to the next node"]
    pub pstNext: *mut LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOS_DL_LIST"][::std::mem::size_of::<LOS_DL_LIST>() - 16usize];
    ["Alignment of LOS_DL_LIST"][::std::mem::align_of::<LOS_DL_LIST>() - 8usize];
    ["Offset of field: LOS_DL_LIST::pstPrev"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstPrev) - 0usize];
    ["Offset of field: LOS_DL_LIST::pstNext"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstNext) - 8usize];
};
pub const SortLinkType_OS_SORT_LINK_TASK: SortLinkType = 1;
pub const SortLinkType_OS_SORT_LINK_SWTMR: SortLinkType = 2;
pub type SortLinkType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SortLinkList {
    pub sortLinkNode: LOS_DL_LIST,
    pub responseTime: UINT64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SortLinkList"][::std::mem::size_of::<SortLinkList>() - 24usize];
    ["Alignment of SortLinkList"][::std::mem::align_of::<SortLinkList>() - 8usize];
    ["Offset of field: SortLinkList::sortLinkNode"]
        [::std::mem::offset_of!(SortLinkList, sortLinkNode) - 0usize];
    ["Offset of field: SortLinkList::responseTime"]
        [::std::mem::offset_of!(SortLinkList, responseTime) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SortLinkAttribute {
    pub sortLink: LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SortLinkAttribute"][::std::mem::size_of::<SortLinkAttribute>() - 16usize];
    ["Alignment of SortLinkAttribute"][::std::mem::align_of::<SortLinkAttribute>() - 8usize];
    ["Offset of field: SortLinkAttribute::sortLink"]
        [::std::mem::offset_of!(SortLinkAttribute, sortLink) - 0usize];
};
unsafe extern "C" {
    pub static mut g_taskSortLink: SortLinkAttribute;
}
unsafe extern "C" {
    pub static mut g_swtmrSortLink: SortLinkAttribute;
}
unsafe extern "C" {
    pub fn OsGetSortLinkAttribute(type_: SortLinkType) -> *mut SortLinkAttribute;
}
unsafe extern "C" {
    pub fn OsSortLinkInit(sortLinkHead: *mut SortLinkAttribute) -> UINT32;
}
unsafe extern "C" {
    pub fn OsAdd2SortLink(
        node: *mut SortLinkList,
        startTime: UINT64,
        waitTicks: UINT32,
        type_: SortLinkType,
    );
}
unsafe extern "C" {
    pub fn OsDeleteSortLink(node: *mut SortLinkList);
}
unsafe extern "C" {
    pub fn OsSortLinkGetTargetExpireTime(
        currTime: UINT64,
        targetSortList: *const SortLinkList,
    ) -> UINT64;
}
unsafe extern "C" {
    pub fn OsSortLinkGetNextExpireTime(sortLinkHead: *const SortLinkAttribute) -> UINT64;
}
unsafe extern "C" {
    pub fn OsSortLinkResponseTimeConvertFreq(oldFreq: UINT32);
}
pub const EnSwTmrType_LOS_SWTMR_MODE_ONCE: EnSwTmrType = 0;
pub const EnSwTmrType_LOS_SWTMR_MODE_PERIOD: EnSwTmrType = 1;
pub const EnSwTmrType_LOS_SWTMR_MODE_NO_SELFDELETE: EnSwTmrType = 2;
pub const EnSwTmrType_LOS_SWTMR_MODE_OPP: EnSwTmrType = 3;
#[doc = " @ingroup los_swtmr\n Software timer mode"]
pub type EnSwTmrType = ::std::os::raw::c_uint;
#[doc = " @ingroup  los_swtmr\n @brief Define the type of a callback function that handles software timer timeout.\n\n @par Description:\n This API is used to define the type of a callback function that handles software timer timeout, so that it can be\n called when software timer timeout.\n\n @attention\n <ul>\n <li>None.</li>\n </ul>\n\n @param  para     [IN] the parameter of the callback function that handles software timer timeout.\n\n @retval None.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see None."]
pub type SWTMR_PROC_FUNC = ::std::option::Option<unsafe extern "C" fn(para: UINT32)>;
#[doc = " @ingroup los_swtmr\n Software timer control structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagSwTmrCtrl {
    pub pstNext: *mut tagSwTmrCtrl,
    pub ucState: UINT8,
    pub ucMode: UINT8,
    pub ucOverrun: UINT8,
    pub usTimerID: UINT32,
    pub uwInterval: UINT32,
    pub uwArg: UINT32,
    pub pfnHandler: SWTMR_PROC_FUNC,
    pub stSortList: SortLinkList,
    pub startTime: UINT64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagSwTmrCtrl"][::std::mem::size_of::<tagSwTmrCtrl>() - 64usize];
    ["Alignment of tagSwTmrCtrl"][::std::mem::align_of::<tagSwTmrCtrl>() - 8usize];
    ["Offset of field: tagSwTmrCtrl::pstNext"]
        [::std::mem::offset_of!(tagSwTmrCtrl, pstNext) - 0usize];
    ["Offset of field: tagSwTmrCtrl::ucState"]
        [::std::mem::offset_of!(tagSwTmrCtrl, ucState) - 8usize];
    ["Offset of field: tagSwTmrCtrl::ucMode"]
        [::std::mem::offset_of!(tagSwTmrCtrl, ucMode) - 9usize];
    ["Offset of field: tagSwTmrCtrl::ucOverrun"]
        [::std::mem::offset_of!(tagSwTmrCtrl, ucOverrun) - 10usize];
    ["Offset of field: tagSwTmrCtrl::usTimerID"]
        [::std::mem::offset_of!(tagSwTmrCtrl, usTimerID) - 12usize];
    ["Offset of field: tagSwTmrCtrl::uwInterval"]
        [::std::mem::offset_of!(tagSwTmrCtrl, uwInterval) - 16usize];
    ["Offset of field: tagSwTmrCtrl::uwArg"][::std::mem::offset_of!(tagSwTmrCtrl, uwArg) - 20usize];
    ["Offset of field: tagSwTmrCtrl::pfnHandler"]
        [::std::mem::offset_of!(tagSwTmrCtrl, pfnHandler) - 24usize];
    ["Offset of field: tagSwTmrCtrl::stSortList"]
        [::std::mem::offset_of!(tagSwTmrCtrl, stSortList) - 32usize];
    ["Offset of field: tagSwTmrCtrl::startTime"]
        [::std::mem::offset_of!(tagSwTmrCtrl, startTime) - 56usize];
};
#[doc = " @ingroup los_swtmr\n Software timer control structure"]
pub type SWTMR_CTRL_S = tagSwTmrCtrl;
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Start a software timer.\n\n @par Description:\n This API is used to start a software timer that has a specified ID.\n @attention\n <ul>\n <li>The specific timer must be created first</li>\n </ul>\n\n @param  swtmrID  [IN] Software timer ID created by LOS_SwtmrCreate.\n\n @retval #LOS_ERRNO_SWTMR_ID_INVALID       Invalid software timer ID.\n @retval #LOS_ERRNO_SWTMR_NOT_CREATED      The software timer is not created.\n @retval #LOS_ERRNO_SWTMR_STATUS_INVALID   Invalid software timer state.\n @retval #LOS_OK                           The software timer is successfully started.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see LOS_SwtmrStop | LOS_SwtmrCreate"]
    pub fn LOS_SwtmrStart(swtmrID: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Stop a software timer.\n\n @par Description:\n This API is used to stop a software timer that has a specified ID.\n @attention\n <ul>\n <li>The specific timer should be created and started firstly.</li>\n </ul>\n\n @param  swtmrID  [IN] Software timer ID created by LOS_SwtmrCreate.\n\n @retval #LOS_ERRNO_SWTMR_ID_INVALID       Invalid software timer ID.\n @retval #LOS_ERRNO_SWTMR_NOT_CREATED      The software timer is not created.\n @retval #LOS_ERRNO_SWTMR_NOT_STARTED      The software timer is not started.\n @retval #LOS_ERRNO_SWTMR_STATUS_INVALID   Invalid software timer state.\n @retval #LOS_OK                           The software timer is successfully stopped.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see LOS_SwtmrStart | LOS_SwtmrCreate"]
    pub fn LOS_SwtmrStop(swtmrID: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Obtain the number of remaining Ticks configured on a software timer.\n\n @par Description:\n This API is used to obtain the number of remaining Ticks configured on the software timer of which the ID is\n specified by usSwTmrID.\n @attention\n <ul>\n <li>The specific timer should be created and started successfully, error happens otherwise.</li>\n </ul>\n\n @param  swtmrID  [IN]  Software timer ID created by LOS_SwtmrCreate.\n @param  tick     [OUT] Number of remaining Ticks configured on the software timer.\n\n @retval #LOS_ERRNO_SWTMR_ID_INVALID      Invalid software timer ID.\n @retval #LOS_ERRNO_SWTMR_NOT_CREATED     The software timer is not created.\n @retval #LOS_ERRNO_SWTMR_NOT_STARTED     The software timer is not started.\n @retval #LOS_ERRNO_SWTMR_STATUS_INVALID  Invalid software timer state.\n @retval #LOS_OK                          The number of remaining Ticks is successfully obtained.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see LOS_SwtmrCreate"]
    pub fn LOS_SwtmrTimeGet(swtmrID: UINT32, tick: *mut UINT32) -> UINT32;
}
unsafe extern "C" {
    pub fn LOS_SwtmrCreate(
        interval: UINT32,
        mode: UINT8,
        handler: SWTMR_PROC_FUNC,
        swtmrID: *mut UINT32,
        arg: UINT32,
    ) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Delete a software timer.\n\n @par Description:\n This API is used to delete a software timer.\n @attention\n <ul>\n <li>The specific timer should be created and then stopped firstly.</li>\n </ul>\n\n @param  swtmrID     [IN] Software timer ID created by LOS_SwtmrCreate.\n\n @retval #LOS_ERRNO_SWTMR_ID_INVALID        Invalid software timer ID.\n @retval #LOS_ERRNO_SWTMR_NOT_CREATED       The software timer is not created.\n @retval #LOS_ERRNO_SWTMR_STATUS_INVALID    Invalid software timer state.\n @retval #LOS_OK                            The software timer is successfully deleted.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see LOS_SwtmrCreate"]
    pub fn LOS_SwtmrDelete(swtmrID: UINT32) -> UINT32;
}
#[doc = "< The software timer is not used."]
pub const SwtmrState_OS_SWTMR_STATUS_UNUSED: SwtmrState = 0;
#[doc = "< The software timer is created."]
pub const SwtmrState_OS_SWTMR_STATUS_CREATED: SwtmrState = 1;
#[doc = "< The software timer is timing."]
pub const SwtmrState_OS_SWTMR_STATUS_TICKING: SwtmrState = 2;
#[doc = " @ingroup los_swtmr\n Software timer state"]
pub type SwtmrState = ::std::os::raw::c_uint;
#[doc = " @ingroup los_swtmr\n Structure of the callback function that handles software timer timeout"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SwtmrHandlerItem {
    #[doc = "< Callback function that handles software timer timeout"]
    pub handler: SWTMR_PROC_FUNC,
    #[doc = "< Parameter passed in when the callback function\nthat handles software timer timeout is called"]
    pub arg: UINT32,
    #[doc = "< The id used to obtain the software timer handle"]
    pub swtmrID: UINT32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SwtmrHandlerItem"][::std::mem::size_of::<SwtmrHandlerItem>() - 16usize];
    ["Alignment of SwtmrHandlerItem"][::std::mem::align_of::<SwtmrHandlerItem>() - 8usize];
    ["Offset of field: SwtmrHandlerItem::handler"]
        [::std::mem::offset_of!(SwtmrHandlerItem, handler) - 0usize];
    ["Offset of field: SwtmrHandlerItem::arg"]
        [::std::mem::offset_of!(SwtmrHandlerItem, arg) - 8usize];
    ["Offset of field: SwtmrHandlerItem::swtmrID"]
        [::std::mem::offset_of!(SwtmrHandlerItem, swtmrID) - 12usize];
};
unsafe extern "C" {
    pub static mut g_swtmrCBArray: *mut SWTMR_CTRL_S;
}
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Initialization software timer.\n\n @par Description:\n <ul>\n <li>This API is used to initialization software.</li>\n </ul>\n @attention\n <ul>\n <li>None.</li>\n </ul>\n\n @param  None.\n\n @retval None.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn OsSwtmrInit() -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_swtmr\n @brief Get next timeout.\n\n @par Description:\n <ul>\n <li>This API is used to get next timeout.</li>\n </ul>\n @attention\n <ul>\n <li>None.</li>\n </ul>\n\n @param  None.\n\n @retval None.\n @par Dependency:\n <ul><li>los_swtmr.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn OsSwtmrGetNextTimeout() -> UINT32;
}
unsafe extern "C" {
    pub fn OsSwtmrResponseTimeReset(startTime: UINT64);
}
