/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
#[doc = " @ingroup los_list\n Structure of a node in a doubly linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOS_DL_LIST {
    #[doc = "< Current node's pointer to the previous node"]
    pub pstPrev: *mut LOS_DL_LIST,
    #[doc = "< Current node's pointer to the next node"]
    pub pstNext: *mut LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOS_DL_LIST"][::std::mem::size_of::<LOS_DL_LIST>() - 8usize];
    ["Alignment of LOS_DL_LIST"][::std::mem::align_of::<LOS_DL_LIST>() - 4usize];
    ["Offset of field: LOS_DL_LIST::pstPrev"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstPrev) - 0usize];
    ["Offset of field: LOS_DL_LIST::pstNext"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstNext) - 4usize];
};
pub const SortLinkType_OS_SORT_LINK_TASK: SortLinkType = 1;
pub const SortLinkType_OS_SORT_LINK_SWTMR: SortLinkType = 2;
pub type SortLinkType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SortLinkList {
    pub sortLinkNode: LOS_DL_LIST,
    pub responseTime: UINT64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SortLinkList"][::std::mem::size_of::<SortLinkList>() - 16usize];
    ["Alignment of SortLinkList"][::std::mem::align_of::<SortLinkList>() - 4usize];
    ["Offset of field: SortLinkList::sortLinkNode"]
        [::std::mem::offset_of!(SortLinkList, sortLinkNode) - 0usize];
    ["Offset of field: SortLinkList::responseTime"]
        [::std::mem::offset_of!(SortLinkList, responseTime) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SortLinkAttribute {
    pub sortLink: LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SortLinkAttribute"][::std::mem::size_of::<SortLinkAttribute>() - 8usize];
    ["Alignment of SortLinkAttribute"][::std::mem::align_of::<SortLinkAttribute>() - 4usize];
    ["Offset of field: SortLinkAttribute::sortLink"]
        [::std::mem::offset_of!(SortLinkAttribute, sortLink) - 0usize];
};
unsafe extern "C" {
    pub static mut g_taskSortLink: SortLinkAttribute;
}
unsafe extern "C" {
    pub fn OsGetSortLinkAttribute(type_: SortLinkType) -> *mut SortLinkAttribute;
}
unsafe extern "C" {
    pub fn OsSortLinkInit(sortLinkHead: *mut SortLinkAttribute) -> UINT32;
}
unsafe extern "C" {
    pub fn OsAdd2SortLink(
        node: *mut SortLinkList,
        startTime: UINT64,
        waitTicks: UINT32,
        type_: SortLinkType,
    );
}
unsafe extern "C" {
    pub fn OsDeleteSortLink(node: *mut SortLinkList);
}
unsafe extern "C" {
    pub fn OsSortLinkGetTargetExpireTime(
        currTime: UINT64,
        targetSortList: *const SortLinkList,
    ) -> UINT64;
}
unsafe extern "C" {
    pub fn OsSortLinkGetNextExpireTime(sortLinkHead: *const SortLinkAttribute) -> UINT64;
}
unsafe extern "C" {
    pub fn OsSortLinkResponseTimeConvertFreq(oldFreq: UINT32);
}
