/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const LOSCFG_BOX_START_PRIO: u32 = 5;
pub const LOSCFG_BOX_PRIO: u32 = 10;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LosBoxCB {
    pub boxStartAddr: UINTPTR,
    pub boxSize: UINTPTR,
    pub boxHeapAddr: UINTPTR,
    pub boxHeapSize: UINTPTR,
    pub boxStackAddr: UINTPTR,
    pub boxStackSize: UINTPTR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LosBoxCB"][::std::mem::size_of::<LosBoxCB>() - 24usize];
    ["Alignment of LosBoxCB"][::std::mem::align_of::<LosBoxCB>() - 4usize];
    ["Offset of field: LosBoxCB::boxStartAddr"]
        [::std::mem::offset_of!(LosBoxCB, boxStartAddr) - 0usize];
    ["Offset of field: LosBoxCB::boxSize"][::std::mem::offset_of!(LosBoxCB, boxSize) - 4usize];
    ["Offset of field: LosBoxCB::boxHeapAddr"]
        [::std::mem::offset_of!(LosBoxCB, boxHeapAddr) - 8usize];
    ["Offset of field: LosBoxCB::boxHeapSize"]
        [::std::mem::offset_of!(LosBoxCB, boxHeapSize) - 12usize];
    ["Offset of field: LosBoxCB::boxStackAddr"]
        [::std::mem::offset_of!(LosBoxCB, boxStackAddr) - 16usize];
    ["Offset of field: LosBoxCB::boxStackSize"]
        [::std::mem::offset_of!(LosBoxCB, boxStackSize) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UserTaskCB {
    pub userArea: ::std::os::raw::c_ulong,
    pub userSp: ::std::os::raw::c_ulong,
    pub boxID: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UserTaskCB"][::std::mem::size_of::<UserTaskCB>() - 12usize];
    ["Alignment of UserTaskCB"][::std::mem::align_of::<UserTaskCB>() - 4usize];
    ["Offset of field: UserTaskCB::userArea"]
        [::std::mem::offset_of!(UserTaskCB, userArea) - 0usize];
    ["Offset of field: UserTaskCB::userSp"][::std::mem::offset_of!(UserTaskCB, userSp) - 4usize];
    ["Offset of field: UserTaskCB::boxID"][::std::mem::offset_of!(UserTaskCB, boxID) - 8usize];
};
unsafe extern "C" {
    pub fn OsUserTaskInit(taskID: UINT32, entry: UINTPTR, userArea: UINTPTR, userSp: UINTPTR);
}
unsafe extern "C" {
    pub fn OsUserTaskDelete(taskID: UINT32);
}
unsafe extern "C" {
    pub fn OsGetUserTaskCB(taskID: UINT32) -> *mut UserTaskCB;
}
unsafe extern "C" {
    pub fn LOS_BoxStart() -> UINT32;
}
unsafe extern "C" {
    pub fn _ulibc_start(main: UINTPTR) -> INT32;
}
