/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
pub const MpuAccessPermission_MPU_RW_BY_PRIVILEGED_ONLY: MpuAccessPermission = 0;
pub const MpuAccessPermission_MPU_RW_ANY: MpuAccessPermission = 1;
pub const MpuAccessPermission_MPU_RO_BY_PRIVILEGED_ONLY: MpuAccessPermission = 2;
pub const MpuAccessPermission_MPU_RO_ANY: MpuAccessPermission = 3;
pub type MpuAccessPermission = ::std::os::raw::c_uint;
pub const MpuExecutable_MPU_EXECUTABLE: MpuExecutable = 0;
pub const MpuExecutable_MPU_NON_EXECUTABLE: MpuExecutable = 1;
pub type MpuExecutable = ::std::os::raw::c_uint;
pub const MpuShareability_MPU_NO_SHARE: MpuShareability = 0;
pub const MpuShareability_MPU_SHARE: MpuShareability = 1;
pub type MpuShareability = ::std::os::raw::c_uint;
pub const MpuMemType_MPU_MEM_ON_CHIP_ROM: MpuMemType = 0;
pub const MpuMemType_MPU_MEM_ON_CHIP_RAM: MpuMemType = 1;
pub const MpuMemType_MPU_MEM_XIP_PSRAM: MpuMemType = 2;
pub const MpuMemType_MPU_MEM_XIP_NOR_FLASH: MpuMemType = 3;
pub const MpuMemType_MPU_MEM_SHARE_MEM: MpuMemType = 4;
pub type MpuMemType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MPU_CFG_PARA {
    pub baseAddr: UINT32,
    pub size: UINT64,
    pub permission: MpuAccessPermission,
    pub executable: MpuExecutable,
    pub shareability: MpuShareability,
    pub memType: MpuMemType,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MPU_CFG_PARA"][::std::mem::size_of::<MPU_CFG_PARA>() - 32usize];
    ["Alignment of MPU_CFG_PARA"][::std::mem::align_of::<MPU_CFG_PARA>() - 8usize];
    ["Offset of field: MPU_CFG_PARA::baseAddr"]
        [::std::mem::offset_of!(MPU_CFG_PARA, baseAddr) - 0usize];
    ["Offset of field: MPU_CFG_PARA::size"][::std::mem::offset_of!(MPU_CFG_PARA, size) - 8usize];
    ["Offset of field: MPU_CFG_PARA::permission"]
        [::std::mem::offset_of!(MPU_CFG_PARA, permission) - 16usize];
    ["Offset of field: MPU_CFG_PARA::executable"]
        [::std::mem::offset_of!(MPU_CFG_PARA, executable) - 20usize];
    ["Offset of field: MPU_CFG_PARA::shareability"]
        [::std::mem::offset_of!(MPU_CFG_PARA, shareability) - 24usize];
    ["Offset of field: MPU_CFG_PARA::memType"]
        [::std::mem::offset_of!(MPU_CFG_PARA, memType) - 28usize];
};
unsafe extern "C" {
    pub fn ArchMpuEnable(defaultRegionEnable: UINT32);
}
unsafe extern "C" {
    pub fn ArchMpuDisable();
}
unsafe extern "C" {
    pub fn ArchMpuSetRegion(regionId: UINT32, para: *mut MPU_CFG_PARA) -> UINT32;
}
unsafe extern "C" {
    pub fn ArchMpuDisableRegion(regionId: UINT32) -> UINT32;
}
unsafe extern "C" {
    pub fn ArchMpuUnusedRegionGet() -> INT32;
}
