/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const OS_SYS_CLOCK: u32 = 1000000;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND: u32 = 100;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND_MINI: u32 = 1000;
pub const LOSCFG_BASE_CORE_TICK_PERIOD_MS: u32 = 10;
pub const LOSCFG_BASE_CORE_TICK_WTIMER: u32 = 0;
pub const LOSCFG_BASE_CORE_TICK_RESPONSE_MAX: u32 = 0;
pub const LOSCFG_PLATFORM_HWI: u32 = 1;
pub const LOSCFG_USE_SYSTEM_DEFINED_INTERRUPT: u32 = 1;
pub const LOSCFG_PLATFORM_HWI_LIMIT: u32 = 32;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_PRIO: u32 = 10;
pub const LOSCFG_BASE_CORE_TSK_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_IDLE_STACK_SIZE: u32 = 384;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_TIMESLICE: u32 = 1;
pub const LOSCFG_BASE_CORE_TIMESLICE_TIMEOUT: u32 = 20000;
pub const LOSCFG_BASE_CORE_TSK_MONITOR: u32 = 0;
pub const LOSCFG_BASE_CORE_EXC_TSK_SWITCH: u32 = 0;
pub const LOS_TASK_PRIORITY_HIGHEST: u32 = 0;
pub const LOS_TASK_PRIORITY_LOWEST: u32 = 31;
pub const LOSCFG_BASE_CORE_TASKSTACK_INDEPENDENT: u32 = 0;
pub const LOSCFG_STACK_POINT_ALIGN_SIZE: u32 = 8;
pub const LOSCFG_BASE_IPC_SEM: u32 = 1;
pub const LOSCFG_BASE_IPC_SEM_LIMIT: u32 = 6;
pub const OS_SEM_COUNTING_MAX_COUNT: u32 = 65535;
pub const LOSCFG_BASE_IPC_MUX: u32 = 1;
pub const LOSCFG_BASE_IPC_MUX_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_QUEUE: u32 = 1;
pub const LOSCFG_BASE_IPC_QUEUE_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_STATIC_QUEUE_LIMIT: u32 = 3;
pub const LOSCFG_BASE_CORE_SWTMR: u32 = 1;
pub const LOSCFG_BASE_CORE_SWTMR_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_SWTMR_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_SWTMR_ALIGN: u32 = 0;
pub const OS_SWTMR_HANDLE_QUEUE_SIZE: u32 = 5;
pub const LOS_COMMON_DIVISOR: u32 = 10;
pub const LOSCFG_SYS_EXTERNAL_HEAP: u32 = 0;
pub const LOSCFG_SYS_HEAP_SIZE: u32 = 65536;
pub const LOSCFG_MEM_MUL_POOL: u32 = 1;
pub const LOSCFG_MEM_FREE_BY_TASKID: u32 = 0;
pub const LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK: u32 = 0;
pub const LOSCFG_MEM_OMIT_LR_CNT: u32 = 4;
pub const LOSCFG_MEM_RECORD_LR_CNT: u32 = 3;
pub const LOSCFG_MEM_LEAKCHECK_RECORD_MAX_NUM: u32 = 1024;
pub const LOSCFG_MEM_WATERLINE: u32 = 1;
pub const OS_SYS_MEM_NUM: u32 = 20;
pub const OS_SYS_NOCACHEMEM_SIZE: u32 = 0;
pub const LOSCFG_MEM_MUL_REGIONS: u32 = 0;
pub const LOSCFG_EXC_HARDWARE_STACK_PROTECTION: u32 = 0;
pub const CMSIS_OS_VER: u32 = 2;
pub const LOSCFG_KERNEL_PRINTF: u32 = 1;
pub const LOSCFG_MPU_ENABLE: u32 = 0;
pub const LOSCFG_TASK_MEM_USED: u32 = 0;
pub const LOSCFG_PLATFORM_HWI_WITH_ARG: u32 = 0;
pub const LOSCFG_ARCH_HWI_VECTOR_ALIGN: u32 = 256;
pub const LOSCFG_KERNEL_SIGNAL: u32 = 0;
pub const LOSCFG_KERNEL_PM: u32 = 0;
pub const LOSCFG_KERNEL_PM_IDLE: u32 = 0;
pub const LOSCFG_SHELL_STACK_SIZE: u32 = 4096;
pub const OS_ERR_MAGIC_WORD: u32 = 2712847352;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static mut m_aucSysMem0: *mut UINT8;
}
#[doc = " @ingroup los_list\n Structure of a node in a doubly linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOS_DL_LIST {
    #[doc = "< Current node's pointer to the previous node"]
    pub pstPrev: *mut LOS_DL_LIST,
    #[doc = "< Current node's pointer to the next node"]
    pub pstNext: *mut LOS_DL_LIST,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOS_DL_LIST"][::std::mem::size_of::<LOS_DL_LIST>() - 8usize];
    ["Alignment of LOS_DL_LIST"][::std::mem::align_of::<LOS_DL_LIST>() - 4usize];
    ["Offset of field: LOS_DL_LIST::pstPrev"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstPrev) - 0usize];
    ["Offset of field: LOS_DL_LIST::pstNext"]
        [::std::mem::offset_of!(LOS_DL_LIST, pstNext) - 4usize];
};
#[doc = " @ingroup los_err\n @brief Define the pointer to the error handling function.\n\n @par Description:\n This API is used to define the pointer to the error handling function.\n @attention\n <ul>\n <li>None.</li>\n </ul>\n\n @param  fileName  [IN] Log file that stores error information.\n @param  lineNo    [IN] Line number of the erroneous line.\n @param  errorNo   [IN] Error code.\n @param  paraLen   [IN] Length of the input parameter pPara.\n @param  para      [IN] User label of the error.\n\n @retval None.\n @par Dependency:\n <ul><li>los_err.h: the header file that contains the API declaration.</li></ul>\n @see None."]
pub type LOS_ERRORHANDLE_FUNC = ::std::option::Option<
    unsafe extern "C" fn(
        fileName: *mut CHAR,
        lineNo: UINT32,
        errorNo: UINT32,
        paraLen: UINT32,
        para: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    #[doc = " @ingroup los_err\n @brief Error handling function.\n\n @par Description:\n This API is used to perform different operations according to error types.\n @attention\n <ul>\n <li>None</li>\n </ul>\n\n @param  fileName  [IN] Log file that stores error information.\n @param  lineNo    [IN] Line number of the erroneous line which should not be OS_ERR_MAGIC_WORD.\n @param  errorNo   [IN] Error code.\n @param  paraLen   [IN] Length of the input parameter pPara.\n @param  para      [IN] User label of the error.\n\n @retval LOS_OK The error is successfully processed.\n @par Dependency:\n <ul><li>los_err.h: the header file that contains the API declaration.</li></ul>\n @see None"]
    pub fn LOS_ErrHandle(
        fileName: *mut CHAR,
        lineNo: UINT32,
        errorNo: UINT32,
        paraLen: UINT32,
        para: *mut ::std::os::raw::c_void,
    ) -> UINT32;
}
#[doc = " @ingroup los_err\n Error handling function structure."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagUserErrFunc {
    #[doc = "< Hook function for error handling."]
    pub pfnHook: LOS_ERRORHANDLE_FUNC,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagUserErrFunc"][::std::mem::size_of::<tagUserErrFunc>() - 4usize];
    ["Alignment of tagUserErrFunc"][::std::mem::align_of::<tagUserErrFunc>() - 4usize];
    ["Offset of field: tagUserErrFunc::pfnHook"]
        [::std::mem::offset_of!(tagUserErrFunc, pfnHook) - 0usize];
};
#[doc = " @ingroup los_err\n Error handling function structure."]
pub type UserErrFunc = tagUserErrFunc;
pub const LOS_MODULE_ID_LOS_MOD_SYS: LOS_MODULE_ID = 0;
pub const LOS_MODULE_ID_LOS_MOD_MEM: LOS_MODULE_ID = 1;
pub const LOS_MODULE_ID_LOS_MOD_TSK: LOS_MODULE_ID = 2;
pub const LOS_MODULE_ID_LOS_MOD_SWTMR: LOS_MODULE_ID = 3;
pub const LOS_MODULE_ID_LOS_MOD_TICK: LOS_MODULE_ID = 4;
pub const LOS_MODULE_ID_LOS_MOD_MSG: LOS_MODULE_ID = 5;
pub const LOS_MODULE_ID_LOS_MOD_QUE: LOS_MODULE_ID = 6;
pub const LOS_MODULE_ID_LOS_MOD_SEM: LOS_MODULE_ID = 7;
pub const LOS_MODULE_ID_LOS_MOD_MBOX: LOS_MODULE_ID = 8;
pub const LOS_MODULE_ID_LOS_MOD_HWI: LOS_MODULE_ID = 9;
pub const LOS_MODULE_ID_LOS_MOD_HWWDG: LOS_MODULE_ID = 10;
pub const LOS_MODULE_ID_LOS_MOD_CACHE: LOS_MODULE_ID = 11;
pub const LOS_MODULE_ID_LOS_MOD_HWTMR: LOS_MODULE_ID = 12;
pub const LOS_MODULE_ID_LOS_MOD_MMU: LOS_MODULE_ID = 13;
pub const LOS_MODULE_ID_LOS_MOD_LOG: LOS_MODULE_ID = 14;
pub const LOS_MODULE_ID_LOS_MOD_ERR: LOS_MODULE_ID = 15;
pub const LOS_MODULE_ID_LOS_MOD_EXC: LOS_MODULE_ID = 16;
pub const LOS_MODULE_ID_LOS_MOD_CSTK: LOS_MODULE_ID = 17;
pub const LOS_MODULE_ID_LOS_MOD_MPU: LOS_MODULE_ID = 18;
pub const LOS_MODULE_ID_LOS_MOD_NMHWI: LOS_MODULE_ID = 19;
pub const LOS_MODULE_ID_LOS_MOD_TRACE: LOS_MODULE_ID = 20;
pub const LOS_MODULE_ID_LOS_MOD_IPC: LOS_MODULE_ID = 24;
pub const LOS_MODULE_ID_LOS_MOD_TIMER: LOS_MODULE_ID = 26;
pub const LOS_MODULE_ID_LOS_MOD_EVENT: LOS_MODULE_ID = 28;
pub const LOS_MODULE_ID_LOS_MOD_MUX: LOS_MODULE_ID = 29;
pub const LOS_MODULE_ID_LOS_MOD_CPUP: LOS_MODULE_ID = 30;
pub const LOS_MODULE_ID_LOS_MOD_HOOK: LOS_MODULE_ID = 31;
pub const LOS_MODULE_ID_LOS_MOD_PM: LOS_MODULE_ID = 32;
pub const LOS_MODULE_ID_LOS_MOD_LMK: LOS_MODULE_ID = 33;
pub const LOS_MODULE_ID_LOS_MOD_SHELL: LOS_MODULE_ID = 49;
pub const LOS_MODULE_ID_LOS_MOD_SIGNAL: LOS_MODULE_ID = 50;
pub const LOS_MODULE_ID_LOS_MOD_BUTT: LOS_MODULE_ID = 51;
pub type LOS_MODULE_ID = ::std::os::raw::c_uint;
pub const LOS_SysSleepEnum_LOS_SYS_NORMAL_SLEEP: LOS_SysSleepEnum = 0;
pub const LOS_SysSleepEnum_LOS_SYS_LIGHT_SLEEP: LOS_SysSleepEnum = 1;
pub const LOS_SysSleepEnum_LOS_SYS_DEEP_SLEEP: LOS_SysSleepEnum = 2;
pub const LOS_SysSleepEnum_LOS_SYS_SHUTDOWN: LOS_SysSleepEnum = 3;
pub type LOS_SysSleepEnum = ::std::os::raw::c_uint;
pub const LOS_PmNodeType_LOS_PM_TYPE_DEVICE: LOS_PmNodeType = 0;
pub const LOS_PmNodeType_LOS_PM_TYPE_TICK_TIMER: LOS_PmNodeType = 1;
pub const LOS_PmNodeType_LOS_PM_TYPE_SYSCTRL: LOS_PmNodeType = 2;
pub type LOS_PmNodeType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LosPmDevice {
    pub suspend: ::std::option::Option<unsafe extern "C" fn(mode: UINT32) -> UINT32>,
    pub resume: ::std::option::Option<unsafe extern "C" fn(mode: UINT32)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LosPmDevice"][::std::mem::size_of::<LosPmDevice>() - 8usize];
    ["Alignment of LosPmDevice"][::std::mem::align_of::<LosPmDevice>() - 4usize];
    ["Offset of field: LosPmDevice::suspend"]
        [::std::mem::offset_of!(LosPmDevice, suspend) - 0usize];
    ["Offset of field: LosPmDevice::resume"][::std::mem::offset_of!(LosPmDevice, resume) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LosPmTickTimer {
    pub freq: UINT32,
    pub timerStart: ::std::option::Option<unsafe extern "C" fn(arg1: UINT64)>,
    pub timerStop: ::std::option::Option<unsafe extern "C" fn()>,
    pub timerCycleGet: ::std::option::Option<unsafe extern "C" fn() -> UINT64>,
    pub tickLock: ::std::option::Option<unsafe extern "C" fn()>,
    pub tickUnlock: ::std::option::Option<unsafe extern "C" fn()>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LosPmTickTimer"][::std::mem::size_of::<LosPmTickTimer>() - 24usize];
    ["Alignment of LosPmTickTimer"][::std::mem::align_of::<LosPmTickTimer>() - 4usize];
    ["Offset of field: LosPmTickTimer::freq"]
        [::std::mem::offset_of!(LosPmTickTimer, freq) - 0usize];
    ["Offset of field: LosPmTickTimer::timerStart"]
        [::std::mem::offset_of!(LosPmTickTimer, timerStart) - 4usize];
    ["Offset of field: LosPmTickTimer::timerStop"]
        [::std::mem::offset_of!(LosPmTickTimer, timerStop) - 8usize];
    ["Offset of field: LosPmTickTimer::timerCycleGet"]
        [::std::mem::offset_of!(LosPmTickTimer, timerCycleGet) - 12usize];
    ["Offset of field: LosPmTickTimer::tickLock"]
        [::std::mem::offset_of!(LosPmTickTimer, tickLock) - 16usize];
    ["Offset of field: LosPmTickTimer::tickUnlock"]
        [::std::mem::offset_of!(LosPmTickTimer, tickUnlock) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LosPmSysctrl {
    pub early: ::std::option::Option<unsafe extern "C" fn(mode: UINT32) -> UINT32>,
    pub late: ::std::option::Option<unsafe extern "C" fn(mode: UINT32)>,
    pub suspendCheck: ::std::option::Option<unsafe extern "C" fn(mode: UINT32)>,
    pub normalSuspend: ::std::option::Option<unsafe extern "C" fn() -> UINT32>,
    pub normalResume: ::std::option::Option<unsafe extern "C" fn()>,
    pub lightSuspend: ::std::option::Option<unsafe extern "C" fn() -> UINT32>,
    pub lightResume: ::std::option::Option<unsafe extern "C" fn()>,
    pub deepSuspend: ::std::option::Option<unsafe extern "C" fn() -> UINT32>,
    pub deepResume: ::std::option::Option<unsafe extern "C" fn()>,
    pub shutdownSuspend: ::std::option::Option<unsafe extern "C" fn() -> UINT32>,
    pub shutdownResume: ::std::option::Option<unsafe extern "C" fn()>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LosPmSysctrl"][::std::mem::size_of::<LosPmSysctrl>() - 44usize];
    ["Alignment of LosPmSysctrl"][::std::mem::align_of::<LosPmSysctrl>() - 4usize];
    ["Offset of field: LosPmSysctrl::early"][::std::mem::offset_of!(LosPmSysctrl, early) - 0usize];
    ["Offset of field: LosPmSysctrl::late"][::std::mem::offset_of!(LosPmSysctrl, late) - 4usize];
    ["Offset of field: LosPmSysctrl::suspendCheck"]
        [::std::mem::offset_of!(LosPmSysctrl, suspendCheck) - 8usize];
    ["Offset of field: LosPmSysctrl::normalSuspend"]
        [::std::mem::offset_of!(LosPmSysctrl, normalSuspend) - 12usize];
    ["Offset of field: LosPmSysctrl::normalResume"]
        [::std::mem::offset_of!(LosPmSysctrl, normalResume) - 16usize];
    ["Offset of field: LosPmSysctrl::lightSuspend"]
        [::std::mem::offset_of!(LosPmSysctrl, lightSuspend) - 20usize];
    ["Offset of field: LosPmSysctrl::lightResume"]
        [::std::mem::offset_of!(LosPmSysctrl, lightResume) - 24usize];
    ["Offset of field: LosPmSysctrl::deepSuspend"]
        [::std::mem::offset_of!(LosPmSysctrl, deepSuspend) - 28usize];
    ["Offset of field: LosPmSysctrl::deepResume"]
        [::std::mem::offset_of!(LosPmSysctrl, deepResume) - 32usize];
    ["Offset of field: LosPmSysctrl::shutdownSuspend"]
        [::std::mem::offset_of!(LosPmSysctrl, shutdownSuspend) - 36usize];
    ["Offset of field: LosPmSysctrl::shutdownResume"]
        [::std::mem::offset_of!(LosPmSysctrl, shutdownResume) - 40usize];
};
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Initialize system low-power frame.\n\n @par Description:\n This API is used to initialize the system low-power frame.\n\n @attention None.\n\n @param  None.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see"]
    pub fn OsPmInit() -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Register a power management node.\n\n @par Description:\n This API is used to register a power management node.\n\n @attention None.\n\n @param  type [IN] The types supported by the PM module.\n @param  node [IN] power management node.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmUnregister"]
    pub fn LOS_PmRegister(type_: LOS_PmNodeType, node: *mut ::std::os::raw::c_void) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Unregister a power management node.\n\n @par Description:\n This API is used to unregister a power management node.\n\n @attention None.\n\n @param  type [IN] The types supported by the PM module.\n @param  node [IN] power management node.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmRegister"]
    pub fn LOS_PmUnregister(type_: LOS_PmNodeType, node: *mut ::std::os::raw::c_void) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Set the system wake up flag.\n\n @par Description:\n This API is used to set the system wake-up flag.\n\n @attention None.\n\n @param None.\n\n @retval None.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see"]
    pub fn LOS_PmWakeSet();
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Get the low-power mode of the current system.\n\n @par Description:\n This API is used to get the low-power mode of the current system.\n\n @attention None.\n\n @param None.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmModeSet"]
    pub fn LOS_PmModeGet() -> LOS_SysSleepEnum;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Set low-power mode.\n\n @par Description:\n This API is used to set low-power mode.\n\n @attention None.\n\n @param  mode [IN] low-power mode.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmModeGet"]
    pub fn LOS_PmModeSet(mode: LOS_SysSleepEnum) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Request to obtain the lock in current mode, so that the system will not enter\n this mode when it enters the idle task next time.\n\n @par Description:\n This API is used to obtain the lock in current mode.\n\n @attention None.\n\n @param  name [IN] Who requests the lock.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmLockRelease"]
    pub fn LOS_PmLockRequest(name: *const CHAR) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Request to obtain the lock in current mode, so that the system will not enter\n this mode when it enters the idle task next time. After the specified interval, the\n lock is automatically released.\n\n @par Description:\n This API is used to obtain the delay lock in current mode.\n\n @attention None.\n\n @param  name        [IN] Who requests the lock.\n @param  millisecond [IN] Specifies the time to automatically release the lock.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmLockRelease"]
    pub fn LOS_PmTimeLockRequest(name: *const CHAR, millisecond: UINT64) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Release the lock in current mode so that the next time the system enters\n the idle task, it will enter this mode.\n\n @par Description:\n This API is used to release the lock in current mode.\n\n @attention None.\n\n @param  name [IN] Who releases the lock.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmLockRequest"]
    pub fn LOS_PmLockRelease(name: *const CHAR) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Gets the current PM lock status.\n\n @par Description:\n This API is used to Get the current PM lock status.\n\n @attention None.\n\n @param None.\n\n @retval Number of awakening sources of the device.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see"]
    pub fn LOS_PmReadLock() -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief The system enters the low-power flow.\n\n @par Description:\n This API is used to enter the system into a low-power process.\n\n @attention None.\n\n @param  wakeCount [IN] Number of wake sources.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see"]
    pub fn LOS_PmSuspend(wakeCount: UINT32) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_pm\n @brief Output the locking information of the pm lock.\n\n @par Description:\n This API is used to output the locking information of the pm lock.\n\n @attention None.\n\n @param None.\n\n @retval error code, LOS_OK means success.\n @par Dependency:\n <ul><li>los_pm.h: the header file that contains the API declaration.</li></ul>\n @see LOS_PmLockRequest"]
    pub fn LOS_PmLockInfoShow();
}
