/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const OS_SYS_CLOCK: u32 = 1000000;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND: u32 = 100;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND_MINI: u32 = 1000;
pub const LOSCFG_BASE_CORE_TICK_PERIOD_MS: u32 = 10;
pub const LOSCFG_BASE_CORE_TICK_WTIMER: u32 = 0;
pub const LOSCFG_BASE_CORE_TICK_RESPONSE_MAX: u32 = 0;
pub const LOSCFG_PLATFORM_HWI: u32 = 1;
pub const LOSCFG_USE_SYSTEM_DEFINED_INTERRUPT: u32 = 1;
pub const LOSCFG_PLATFORM_HWI_LIMIT: u32 = 32;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_PRIO: u32 = 10;
pub const LOSCFG_BASE_CORE_TSK_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_IDLE_STACK_SIZE: u32 = 384;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_TIMESLICE: u32 = 1;
pub const LOSCFG_BASE_CORE_TIMESLICE_TIMEOUT: u32 = 20000;
pub const LOSCFG_BASE_CORE_TSK_MONITOR: u32 = 0;
pub const LOSCFG_BASE_CORE_EXC_TSK_SWITCH: u32 = 0;
pub const LOS_TASK_PRIORITY_HIGHEST: u32 = 0;
pub const LOS_TASK_PRIORITY_LOWEST: u32 = 31;
pub const LOSCFG_BASE_CORE_TASKSTACK_INDEPENDENT: u32 = 0;
pub const LOSCFG_STACK_POINT_ALIGN_SIZE: u32 = 8;
pub const LOSCFG_BASE_IPC_SEM: u32 = 1;
pub const LOSCFG_BASE_IPC_SEM_LIMIT: u32 = 6;
pub const OS_SEM_COUNTING_MAX_COUNT: u32 = 65535;
pub const LOSCFG_BASE_IPC_MUX: u32 = 1;
pub const LOSCFG_BASE_IPC_MUX_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_QUEUE: u32 = 1;
pub const LOSCFG_BASE_IPC_QUEUE_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_STATIC_QUEUE_LIMIT: u32 = 3;
pub const LOSCFG_BASE_CORE_SWTMR: u32 = 1;
pub const LOSCFG_BASE_CORE_SWTMR_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_SWTMR_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_SWTMR_ALIGN: u32 = 0;
pub const OS_SWTMR_HANDLE_QUEUE_SIZE: u32 = 5;
pub const LOS_COMMON_DIVISOR: u32 = 10;
pub const LOSCFG_SYS_EXTERNAL_HEAP: u32 = 0;
pub const LOSCFG_SYS_HEAP_SIZE: u32 = 65536;
pub const LOSCFG_MEM_MUL_POOL: u32 = 1;
pub const LOSCFG_MEM_FREE_BY_TASKID: u32 = 0;
pub const LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK: u32 = 0;
pub const LOSCFG_MEM_OMIT_LR_CNT: u32 = 4;
pub const LOSCFG_MEM_RECORD_LR_CNT: u32 = 3;
pub const LOSCFG_MEM_LEAKCHECK_RECORD_MAX_NUM: u32 = 1024;
pub const LOSCFG_MEM_WATERLINE: u32 = 1;
pub const OS_SYS_MEM_NUM: u32 = 20;
pub const OS_SYS_NOCACHEMEM_SIZE: u32 = 0;
pub const LOSCFG_MEM_MUL_REGIONS: u32 = 0;
pub const LOSCFG_EXC_HARDWARE_STACK_PROTECTION: u32 = 0;
pub const CMSIS_OS_VER: u32 = 2;
pub const LOSCFG_KERNEL_PRINTF: u32 = 1;
pub const LOSCFG_MPU_ENABLE: u32 = 0;
pub const LOSCFG_TASK_MEM_USED: u32 = 0;
pub const LOSCFG_PLATFORM_HWI_WITH_ARG: u32 = 0;
pub const LOSCFG_ARCH_HWI_VECTOR_ALIGN: u32 = 256;
pub const LOSCFG_KERNEL_SIGNAL: u32 = 0;
pub const LOSCFG_KERNEL_PM: u32 = 0;
pub const LOSCFG_KERNEL_PM_IDLE: u32 = 0;
pub const LOSCFG_SHELL_STACK_SIZE: u32 = 4096;
pub const LOG_EMG_LEVEL: u32 = 0;
pub const LOG_COMMON_LEVEL: u32 = 1;
pub const LOG_ERR_LEVEL: u32 = 2;
pub const LOG_WARN_LEVEL: u32 = 3;
pub const LOG_INFO_LEVEL: u32 = 4;
pub const LOG_DEBUG_LEVEL: u32 = 5;
pub const PRINT_LEVEL: u32 = 2;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static mut m_aucSysMem0: *mut UINT8;
}
pub const EXC_TYPE_EXC_REBOOT: EXC_TYPE = 0;
pub const EXC_TYPE_EXC_ASSERT: EXC_TYPE = 1;
pub const EXC_TYPE_EXC_PANIC: EXC_TYPE = 2;
pub const EXC_TYPE_EXC_STACKOVERFLOW: EXC_TYPE = 3;
pub const EXC_TYPE_EXC_INTERRUPT: EXC_TYPE = 4;
pub const EXC_TYPE_EXC_TYPE_END: EXC_TYPE = 5;
pub type EXC_TYPE = ::std::os::raw::c_uint;
pub type ExcHookFn = ::std::option::Option<unsafe extern "C" fn(excType: EXC_TYPE)>;
unsafe extern "C" {
    pub fn OsExcHookRegister(excHookFn: ExcHookFn);
}
unsafe extern "C" {
    pub fn OsDoExcHook(excType: EXC_TYPE);
}
pub const LogModuleType_LOG_MODULE_KERNEL: LogModuleType = 0;
pub const LogModuleType_LOG_MODULE_FS: LogModuleType = 1;
pub const LogModuleType_LOS_MODULE_OTHERS: LogModuleType = 2;
pub type LogModuleType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn printf(fmt: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn OsLogLevelCheck(level: INT32) -> INT32;
}
pub type BACK_TRACE_HOOK = ::std::option::Option<
    unsafe extern "C" fn(LR: *mut UINTPTR, LRSize: UINT32, jumpCount: UINT32, SP: UINTPTR),
>;
unsafe extern "C" {
    pub fn OsBackTraceHookSet(hook: BACK_TRACE_HOOK);
}
unsafe extern "C" {
    pub fn OsBackTraceHookCall(LR: *mut UINTPTR, LRSize: UINT32, jumpCount: UINT32, SP: UINTPTR);
}
#[doc = " @ingroup los_membox\n Structure of a free node in a memory pool"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagMEMBOX_NODE {
    #[doc = "< Free node's pointer to the next node in a memory pool"]
    pub pstNext: *mut tagMEMBOX_NODE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagMEMBOX_NODE"][::std::mem::size_of::<tagMEMBOX_NODE>() - 4usize];
    ["Alignment of tagMEMBOX_NODE"][::std::mem::align_of::<tagMEMBOX_NODE>() - 4usize];
    ["Offset of field: tagMEMBOX_NODE::pstNext"]
        [::std::mem::offset_of!(tagMEMBOX_NODE, pstNext) - 0usize];
};
#[doc = " @ingroup los_membox\n Structure of a free node in a memory pool"]
pub type LOS_MEMBOX_NODE = tagMEMBOX_NODE;
#[doc = " @ingroup los_membox\n Memory pool information structure"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOS_MEMBOX_INFO {
    #[doc = "< Block size"]
    pub uwBlkSize: UINT32,
    #[doc = "< Block number"]
    pub uwBlkNum: UINT32,
    #[doc = "< The number of allocated blocks"]
    pub uwBlkCnt: UINT32,
    #[doc = "< Free list"]
    pub stFreeList: LOS_MEMBOX_NODE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOS_MEMBOX_INFO"][::std::mem::size_of::<LOS_MEMBOX_INFO>() - 16usize];
    ["Alignment of LOS_MEMBOX_INFO"][::std::mem::align_of::<LOS_MEMBOX_INFO>() - 4usize];
    ["Offset of field: LOS_MEMBOX_INFO::uwBlkSize"]
        [::std::mem::offset_of!(LOS_MEMBOX_INFO, uwBlkSize) - 0usize];
    ["Offset of field: LOS_MEMBOX_INFO::uwBlkNum"]
        [::std::mem::offset_of!(LOS_MEMBOX_INFO, uwBlkNum) - 4usize];
    ["Offset of field: LOS_MEMBOX_INFO::uwBlkCnt"]
        [::std::mem::offset_of!(LOS_MEMBOX_INFO, uwBlkCnt) - 8usize];
    ["Offset of field: LOS_MEMBOX_INFO::stFreeList"]
        [::std::mem::offset_of!(LOS_MEMBOX_INFO, stFreeList) - 12usize];
};
#[doc = " @ingroup los_membox\n Memory pool information structure"]
pub type OS_MEMBOX_S = LOS_MEMBOX_INFO;
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief Initialize a memory pool.\n\n @par Description:\n <ul>\n <li>This API is used to initialize a memory pool.</li>\n </ul>\n @attention\n <ul>\n <li>The poolSize parameter value should match the following two conditions :\n 1) Be less than or equal to the Memory pool size;\n 2) Be greater than the size of LOS_MEMBOX_INFO.</li>\n </ul>\n\n @param pool     [IN] Memory pool address.\n @param poolSize [IN] Memory pool size.\n @param blkSize  [IN] Memory block size.\n\n @retval #LOS_NOK   The memory pool fails to be initialized.\n @retval #LOS_OK    The memory pool is successfully initialized.\n @par Dependency:\n <ul>\n <li>los_membox.h: the header file that contains the API declaration.</li>\n </ul>\n @see None."]
    pub fn LOS_MemboxInit(
        pool: *mut ::std::os::raw::c_void,
        poolSize: UINT32,
        blkSize: UINT32,
    ) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief Request a memory block.\n\n @par Description:\n <ul>\n <li>This API is used to request a memory block.</li>\n </ul>\n @attention\n <ul>\n <li>The input pool parameter must be initialized via func LOS_MemboxInit.</li>\n </ul>\n\n @param pool    [IN] Memory pool address.\n\n @retval #VOID*      The request is accepted, and return a memory block address.\n @retval #NULL       The request fails.\n @par Dependency:\n <ul>\n <li>los_membox.h: the header file that contains the API declaration.</li>\n </ul>\n @see LOS_MemboxFree"]
    pub fn LOS_MemboxAlloc(pool: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief Free a memory block.\n\n @par Description:\n <ul>\n <li>This API is used to free a memory block.</li>\n </ul>\n @attention\n <ul>\n <li>The input pool parameter must be initialized via func LOS_MemboxInit.</li>\n <li>The input box parameter must be allocated by LOS_MemboxAlloc.</li>\n </ul>\n\n @param pool     [IN] Memory pool address.\n @param box      [IN] Memory block address.\n\n @retval #LOS_NOK   This memory block fails to be freed.\n @retval #LOS_OK    This memory block is successfully freed.\n @par Dependency:\n <ul>\n <li>los_membox.h: the header file that contains the API declaration.</li>\n </ul>\n @see LOS_MemboxAlloc"]
    pub fn LOS_MemboxFree(
        pool: *mut ::std::os::raw::c_void,
        box_: *mut ::std::os::raw::c_void,
    ) -> UINT32;
}
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief Clear a memory block.\n\n @par Description:\n <ul>\n <li>This API is used to set the memory block value to be 0.</li>\n </ul>\n @attention\n <ul>\n <li>The input pool parameter must be initialized via func LOS_MemboxInit.</li>\n <li>The input box parameter must be allocated by LOS_MemboxAlloc.</li>\n </ul>\n\n @param pool    [IN] Memory pool address.\n @param box     [IN] Memory block address.\n\n @retval VOID\n @par Dependency:\n <ul>\n <li>los_membox.h: the header file that contains the API declaration.</li>\n </ul>\n @see None."]
    pub fn LOS_MemboxClr(pool: *mut ::std::os::raw::c_void, box_: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief show membox info.\n\n @par Description:\n <ul>\n <li>This API is used to show the memory pool info.</li>\n </ul>\n @attention\n <ul>\n <li>The input pool parameter must be initialized via func LOS_MemboxInit.</li>\n </ul>\n\n @param pool    [IN] Memory pool address.\n\n @retval VOID\n @par Dependency:\n <ul>\n <li>los_membox.h: the header file that contains the API declaration.</li>\n </ul>\n @see None."]
    pub fn LOS_ShowBox(pool: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    #[doc = " @ingroup los_membox\n @brief calculate membox information.\n\n @par Description:\n <ul>\n <li>This API is used to calculate membox information.</li>\n </ul>\n @attention\n <ul>\n <li>One parameter of this interface is a pointer, it should be a correct value, otherwise, the system may\n be abnormal.</li>\n </ul>\n\n @param  boxMem        [IN]  Type  #VOID*   Pointer to the calculate membox.\n @param  maxBlk       [OUT] Type  #UINT32* Record membox max block.\n @param  blkCnt       [OUT] Type  #UINT32* Record membox block count already allocated.\n @param  blkSize      [OUT] Type  #UINT32* Record membox block size.\n\n @retval #LOS_OK        The heap status calculate success.\n @retval #LOS_NOK       The membox  status calculate with some error.\n @par Dependency:\n <ul><li>los_memory.h: the header file that contains the API declaration.</li></ul>\n @see LOS_MemAlloc | LOS_MemRealloc | LOS_MemFree"]
    pub fn LOS_MemboxStatisticsGet(
        boxMem: *const ::std::os::raw::c_void,
        maxBlk: *mut UINT32,
        blkCnt: *mut UINT32,
        blkSize: *mut UINT32,
    ) -> UINT32;
}
