/* automatically generated by rust-bindgen 0.72.1 */

pub const OS_LITTLE_ENDIAN: u32 = 4660;
pub const OS_BIG_ENDIAN: u32 = 17185;
pub const OS_BYTE_ORDER: u32 = 4660;
pub const LOS_OK: u32 = 0;
pub const OS_FAIL: u32 = 1;
pub const OS_64BIT_MAX: i32 = -1;
pub const __LIBATOMIC_N_LOCKS: u32 = 16;
pub const OS_SYS_CLOCK: u32 = 1000000;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND: u32 = 100;
pub const LOSCFG_BASE_CORE_TICK_PER_SECOND_MINI: u32 = 1000;
pub const LOSCFG_BASE_CORE_TICK_PERIOD_MS: u32 = 10;
pub const LOSCFG_BASE_CORE_TICK_WTIMER: u32 = 0;
pub const LOSCFG_BASE_CORE_TICK_RESPONSE_MAX: u32 = 0;
pub const LOSCFG_PLATFORM_HWI: u32 = 1;
pub const LOSCFG_USE_SYSTEM_DEFINED_INTERRUPT: u32 = 1;
pub const LOSCFG_PLATFORM_HWI_LIMIT: u32 = 32;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_PRIO: u32 = 10;
pub const LOSCFG_BASE_CORE_TSK_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_IDLE_STACK_SIZE: u32 = 384;
pub const LOSCFG_BASE_CORE_TSK_DEFAULT_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_TIMESLICE: u32 = 1;
pub const LOSCFG_BASE_CORE_TIMESLICE_TIMEOUT: u32 = 20000;
pub const LOSCFG_BASE_CORE_TSK_MONITOR: u32 = 0;
pub const LOSCFG_BASE_CORE_EXC_TSK_SWITCH: u32 = 0;
pub const LOS_TASK_PRIORITY_HIGHEST: u32 = 0;
pub const LOS_TASK_PRIORITY_LOWEST: u32 = 31;
pub const LOSCFG_BASE_CORE_TASKSTACK_INDEPENDENT: u32 = 0;
pub const LOSCFG_STACK_POINT_ALIGN_SIZE: u32 = 8;
pub const LOSCFG_BASE_IPC_SEM: u32 = 1;
pub const LOSCFG_BASE_IPC_SEM_LIMIT: u32 = 6;
pub const OS_SEM_COUNTING_MAX_COUNT: u32 = 65535;
pub const LOSCFG_BASE_IPC_MUX: u32 = 1;
pub const LOSCFG_BASE_IPC_MUX_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_QUEUE: u32 = 1;
pub const LOSCFG_BASE_IPC_QUEUE_LIMIT: u32 = 6;
pub const LOSCFG_BASE_IPC_STATIC_QUEUE_LIMIT: u32 = 3;
pub const LOSCFG_BASE_CORE_SWTMR: u32 = 1;
pub const LOSCFG_BASE_CORE_SWTMR_LIMIT: u32 = 5;
pub const LOSCFG_BASE_CORE_TSK_SWTMR_STACK_SIZE: u32 = 1024;
pub const LOSCFG_BASE_CORE_SWTMR_ALIGN: u32 = 0;
pub const OS_SWTMR_HANDLE_QUEUE_SIZE: u32 = 5;
pub const LOS_COMMON_DIVISOR: u32 = 10;
pub const LOSCFG_SYS_EXTERNAL_HEAP: u32 = 0;
pub const LOSCFG_SYS_HEAP_SIZE: u32 = 65536;
pub const LOSCFG_MEM_MUL_POOL: u32 = 1;
pub const LOSCFG_MEM_FREE_BY_TASKID: u32 = 0;
pub const LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK: u32 = 0;
pub const LOSCFG_MEM_OMIT_LR_CNT: u32 = 4;
pub const LOSCFG_MEM_RECORD_LR_CNT: u32 = 3;
pub const LOSCFG_MEM_LEAKCHECK_RECORD_MAX_NUM: u32 = 1024;
pub const LOSCFG_MEM_WATERLINE: u32 = 1;
pub const OS_SYS_MEM_NUM: u32 = 20;
pub const OS_SYS_NOCACHEMEM_SIZE: u32 = 0;
pub const LOSCFG_MEM_MUL_REGIONS: u32 = 0;
pub const LOSCFG_EXC_HARDWARE_STACK_PROTECTION: u32 = 0;
pub const CMSIS_OS_VER: u32 = 2;
pub const LOSCFG_KERNEL_PRINTF: u32 = 1;
pub const LOSCFG_MPU_ENABLE: u32 = 0;
pub const LOSCFG_TASK_MEM_USED: u32 = 0;
pub const LOSCFG_PLATFORM_HWI_WITH_ARG: u32 = 0;
pub const LOSCFG_ARCH_HWI_VECTOR_ALIGN: u32 = 256;
pub const LOSCFG_KERNEL_SIGNAL: u32 = 0;
pub const LOSCFG_KERNEL_PM: u32 = 0;
pub const LOSCFG_KERNEL_PM_IDLE: u32 = 0;
pub const LOSCFG_SHELL_STACK_SIZE: u32 = 4096;
pub const PSR_T_ARM: u32 = 0;
pub const PSR_T_THUMB: u32 = 32;
pub const PSR_MODE_SVC: u32 = 19;
pub const PSR_MODE_SYS: u32 = 31;
pub const PSR_MODE_SVC_THUMB: u32 = 51;
pub const PSR_MODE_SVC_ARM: u32 = 19;
pub const PSR_MODE_SYS_THUMB: u32 = 63;
pub const PSR_MODE_SYS_ARM: u32 = 31;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type FLOAT = f32;
pub type DOUBLE = f64;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINTPTR = ::std::os::raw::c_uint;
pub type INTPTR = ::std::os::raw::c_int;
pub type Atomic = INT32;
pub type Atomic64 = INT64;
pub type BOOL = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static mut m_aucSysMem0: *mut UINT8;
}
unsafe extern "C" {
    pub fn OsTaskEntryArm();
}
unsafe extern "C" {
    pub fn OsTaskEntryThumb();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TagTskContext {
    pub spsr: UINT32,
    pub r0: UINT32,
    pub r1: UINT32,
    pub r2: UINT32,
    pub r3: UINT32,
    pub r4: UINT32,
    pub r5: UINT32,
    pub r6: UINT32,
    pub r7: UINT32,
    pub r8: UINT32,
    pub r9: UINT32,
    pub r10: UINT32,
    pub r11: UINT32,
    pub r12: UINT32,
    pub sp: UINT32,
    pub lr: UINT32,
    pub pc: UINT32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of TagTskContext"][::std::mem::size_of::<TagTskContext>() - 68usize];
    ["Alignment of TagTskContext"][::std::mem::align_of::<TagTskContext>() - 4usize];
    ["Offset of field: TagTskContext::spsr"][::std::mem::offset_of!(TagTskContext, spsr) - 0usize];
    ["Offset of field: TagTskContext::r0"][::std::mem::offset_of!(TagTskContext, r0) - 4usize];
    ["Offset of field: TagTskContext::r1"][::std::mem::offset_of!(TagTskContext, r1) - 8usize];
    ["Offset of field: TagTskContext::r2"][::std::mem::offset_of!(TagTskContext, r2) - 12usize];
    ["Offset of field: TagTskContext::r3"][::std::mem::offset_of!(TagTskContext, r3) - 16usize];
    ["Offset of field: TagTskContext::r4"][::std::mem::offset_of!(TagTskContext, r4) - 20usize];
    ["Offset of field: TagTskContext::r5"][::std::mem::offset_of!(TagTskContext, r5) - 24usize];
    ["Offset of field: TagTskContext::r6"][::std::mem::offset_of!(TagTskContext, r6) - 28usize];
    ["Offset of field: TagTskContext::r7"][::std::mem::offset_of!(TagTskContext, r7) - 32usize];
    ["Offset of field: TagTskContext::r8"][::std::mem::offset_of!(TagTskContext, r8) - 36usize];
    ["Offset of field: TagTskContext::r9"][::std::mem::offset_of!(TagTskContext, r9) - 40usize];
    ["Offset of field: TagTskContext::r10"][::std::mem::offset_of!(TagTskContext, r10) - 44usize];
    ["Offset of field: TagTskContext::r11"][::std::mem::offset_of!(TagTskContext, r11) - 48usize];
    ["Offset of field: TagTskContext::r12"][::std::mem::offset_of!(TagTskContext, r12) - 52usize];
    ["Offset of field: TagTskContext::sp"][::std::mem::offset_of!(TagTskContext, sp) - 56usize];
    ["Offset of field: TagTskContext::lr"][::std::mem::offset_of!(TagTskContext, lr) - 60usize];
    ["Offset of field: TagTskContext::pc"][::std::mem::offset_of!(TagTskContext, pc) - 64usize];
};
pub type TaskContext = TagTskContext;
unsafe extern "C" {
    #[doc = " @ingroup  los_config\n @brief: Task start running function.\n\n @par Description:\n This API is used to start a task.\n\n @attention:\n <ul><li>None.</li></ul>\n\n @param: None.\n\n @retval None.\n\n @par Dependency:\n <ul><li>los_config.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn HalStartToRun();
}
unsafe extern "C" {
    #[doc = " @ingroup los_arch_context\n @brief Wait for interrupt.\n\n @par Description:\n <ul>\n <li>This API is used to suspend execution until interrupt or a debug request occurs.</li>\n </ul>\n @attention None.\n\n @param None.\n\n @retval: None.\n\n @par Dependency:\n los_arch_context.h: the header file that contains the API declaration.\n @see None."]
    pub fn wfi();
}
unsafe extern "C" {
    #[doc = " @ingroup los_arch_context\n @brief: mem fence function.\n\n @par Description:\n This API is used to fence for memory.\n\n @attention:\n <ul><li>None.</li></ul>\n\n @param: None.\n\n @retval:None.\n @par Dependency:\n <ul><li>los_arch_context.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn dmb();
}
unsafe extern "C" {
    #[doc = " @ingroup los_arch_context\n @brief: mem fence function.\n\n @par Description:\n This API is same as dmb, it just for adaptation.\n\n @attention:\n <ul><li>None.</li></ul>\n\n @param: None.\n\n @retval:None.\n @par Dependency:\n <ul><li>los_arch_context.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn dsb();
}
unsafe extern "C" {
    #[doc = " @ingroup los_arch_context\n @brief: instruction fence function.\n\n @par Description:\n This API is used to fence for instruction.\n\n @attention:\n <ul><li>None.</li></ul>\n\n @param: None.\n\n @retval:None.\n @par Dependency:\n <ul><li>los_arch_context.h: the header file that contains the API declaration.</li></ul>\n @see None."]
    pub fn isb();
}
